"""Minimal loading of `.env.production`/`.env` from the monorepo root, without overwriting
variables already present in the process environment.

Why this lives here: before the migration to `cerebro-cli`, the user had a
`.venv\\Scripts\\cerebro.cmd` wrapper that they (not this parser.py) generated by hand --
it loaded `.env.production` (which points the CLI at the VPS via
`KNOWLEDGEOS_API_URL`/`KNOWLEDGEOS_API_TOKEN`, a legacy that `cerebro_clients.config`
still accepts as a fallback) and then delegated to the real binary. When installing
`cerebro-cli` with `pip install -e`, the `cerebro.exe` entry point that setuptools generates
wins on the PATH over that `.cmd` (PATHEXT resolves `.exe` before `.cmd`), so the
wrapper stops running even though it's still present -- without this module, `cerebro memory
stats` would stop talking to the VPS by default without the user having changed anything.
This module reproduces that loading INSIDE the CLI itself so the behavior doesn't
depend on a hand-generated shell wrapper.

Only takes effect in an editable install inside the monorepo (where `packages/`
exists relative to this file): if `cerebro-cli` were installed outside this repo (e.g.
published to an index), `.env.production`/`.env` simply wouldn't be found under
`REPO_ROOT` and `load_repo_dotenv()` would do nothing -- it's not a deployment
requirement, it's a convenience for the user's current dev environment.

Deliberately minimal parser (no new dependency like python-dotenv): one line
per variable, `KEY=value`, comments with `#` (whole line or trailing after a
space) and blank lines are ignored. Doesn't support variable interpolation or
multiline values -- none of this repo's .env files need them.
"""

from __future__ import annotations

import os
from pathlib import Path

# packages/cerebro-cli/src/cerebro_cli/dotenv.py -> parents[4] is the monorepo
# root (same calculation as REPO_ROOT in shared_commands.py).
REPO_ROOT = Path(__file__).resolve().parents[4]


def parse_dotenv(text: str) -> dict[str, str]:
    """Parses the contents of a .env file into a dict, in the order the
    keys appear. Blank lines and comments (`#...`) are ignored; a line without `=` is
    ignored too (it's not a valid key/value pair)."""
    result: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # optional surrounding quotes, as in a typical .env file
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        if key:
            result[key] = value
    return result


def _apply_without_overwriting(values: dict[str, str], env: dict[str, str]) -> None:
    for key, value in values.items():
        env.setdefault(key, value)


def load_repo_dotenv(repo_root: Path | None = None, *, env: dict[str, str] | None = None) -> None:
    """Loads `.env.production` and then `.env` from the monorepo root, WITHOUT overwriting
    any variable already present in `env` (default: `os.environ`) -- neither one that was
    already set before calling this function, nor one that `.env.production` already set by
    being processed first. That's why order matters: `.env.production` wins over `.env`
    when both define the same key, and any variable the user exported by hand
    wins over both.
    """
    root = repo_root if repo_root is not None else REPO_ROOT
    target_env = env if env is not None else os.environ

    for filename in (".env.production", ".env"):
        path = root / filename
        if not path.exists():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        _apply_without_overwriting(parse_dotenv(text), target_env)
